### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by Atteqany** [axtolm/pm-training-directly-follows-graph#1]
Traceback (most recent call last):
  File "C:\Users\InfoSys\.conda\envs\infosys\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 554, in _run_script
    exec(code, module.__dict__)
  File "Z:\Bonus-directly-follows-graph\pm-training-directly-follows-graph.py", line 21, in <module>
    initial_sidebar_state="expanded")
  File "C:\Users\InfoSys\.conda\envs\infosys\lib\site-packages\streamlit\commands\page_config.py", line 162, in set_page_config
    ctx.enqueue(msg)
  File "C:\Users\InfoSys\.conda\envs\infosys\lib\site-packages\streamlit\scriptrunner\script_run_context.py", line 78, in enqueue
    + "(https://docs.streamlit.io/library/api-reference/utilities/st.set_page_config)."
streamlit.errors.StreamlitAPIException: `set_page_config()` can only be called once per app, and must be called as the first Streamlit command in your script.

For more information refer to the [docs](https://docs.streamlit.io/library/api-reference/utilities/st.set_page_config).

**Comment by Atteqany** [comment]
In the browser it gives this error 

Traceback:
File "Z:\Bonus-directly-follows-graph\pm-training-directly-follows-graph.py", line 24, in <module>
    initial_sidebar_state="expanded")Traceback:

**Comment by axtolm** [comment]
Hello, thank you for your request. I tried to reproduce your case, but couldn't.
Can you describe your Python environment used for deployment and post a code repository?

**Comment by Atteqany** [comment]
I appreciate your responding 
I’m running Spyder Anaconda

**Comment by axtolm** [comment]
In this case, you can use Anaconda Spyder to edit Python code.
To run my application you need to use Anaconda Powershell Prompt.
This app is based on the streamlit framework and works as a local web application.

You can try the following steps:
1. On Windows (do you use this OS?) download and install grapviz package (https://graphviz.org/download/) 
2. Launch Anaconda Powershell Prompt.
3. Create a new environment (`pm` is the name of this environment):
`conda create -n pm python=3.11`
4. Activate it:
`conda activate pm`
5. Update pip:
`python.exe -m pip install --upgrade pip`
6. Install the streamlit and grapviz packages:
`pip install streamlit`
`pip install graphviz`
7. Download the Python file with my app to your folder. 
For instance - `D:\Bonus-directly-follows-graph\directly_follows_graph.py`
8. Run the app in the Anaconda Powershell Prompt:
`streamlit run D:\Bonus-directly-follows-graph\directly_follows_graph.py`

You need to do all these operations on the command line.

**Comment by Atteqany** [comment]
Appreciate your help, I followed like these instructions from beginning but with variant errors. 
After 5 hours the problem has solved by adding all the folders which appear in the exceptions in the path manager of Spyder.

thank you very much.
